FROM python:3.9-slim

# Установка системных зависимостей
RUN apt-get update && apt-get install -y git ffmpeg && apt-get clean

RUN pip install "numpy<2"

# Установка PyTorch для CPU
RUN pip install torch==1.9.1 torchvision==0.10.1 torchaudio==0.9.1

# Установка TensorFlow и нужной версии protobuf
RUN pip install tensorflow==2.8.0 protobuf==3.20.*

# Установка basic-pitch из репозитория
RUN pip install git+https://github.com/spotify/basic-pitch.git

WORKDIR /app

ENTRYPOINT ["basic-pitch"]
